-- auto Generated on 2020-01-26 21:58:47 
-- DROP TABLE IF EXISTS `nation`; 
CREATE TABLE nation(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'name',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'nation';
